version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: college_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: college_db
      JWT_SECRET: your_jwt_secret_here
      USERNAME: admin
      PASS: pass123
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata:
